### ISSUE TITLE
sidekiq_options lock conflicts with sidekiq-unique-jobs gem lock option

### ISSUE THREAD

**Issue by recurator** [rwojsznis/sidekiq-lock#15]
Hello,

Gem [sidekiq-lock](https://github.com/rwojsznis/sidekiq-lock) and [sidekiq-unique-jobs](https://github.com/mhenrixon/sidekiq-unique-jobs) use the same option
[sidekiq_options lock: :until_executing](https://github.com/mhenrixon/sidekiq-unique-jobs#locks)
[sidekiq_options lock: { timeout: 1000, name: 'project_status_lock' }](https://github.com/rwojsznis/sidekiq-lock#usage)
 which causes an error: 
`NoMethodError: undefined method to_sym for {:timeout=>10000, :name=>"project_status_lock"}:Hash
Did you mean?  to_s, to_set
/usr/local/bundle/gems/sidekiq-unique-jobs-6.0.13/lib/sidekiq_unique_jobs/options_with_fallback.rb:52:in lock_class'`
because `sidekiq-unique-jobs` does not expect Hash as lock option value which need to be defined as hash in sidekiq-lock.

So far, I have not found a way to make these two gems work together.

**Comment by rwojsznis** [comment]
Hey @recurator 👋 `sidekiq-unique-jobs` is way way more powerful and covers _a lot_ of different use cases - why would you want to use both gems simultaneously? Maybe you could provide some example? 🤔

**Comment by rwojsznis** [comment]
Thanks for the details!

It seems you're covered by `sidekiq-unique-jobs` already then! Please look into their `:while_executing` lock option - with proper `lock_ttl` value you should be able to achieve what you aiming for and you don't really need my gem for it :) (you might also need `lock_args_method`, heavly depends on your implementation)

**Comment by recurator** [comment]
Thank you @rwojsznis
