### ISSUE TITLE
Want to initialize multiple locks (mutex) in a single sidekiq job and set there expiration time to infinite. 

### ISSUE THREAD

**Issue by abdul-wahab-qbatch** [rwojsznis/sidekiq-lock#17]
Something like. 

  include Sidekiq::Lock::Worker
  sidekiq_options lock: [{ timeout: nil, name: 'lock-worker1' }, { timeout: nil, name: 'lock-worker2' }]

**Comment by rwojsznis** [comment]
Hey there! [This was discussed back in 2014](https://github.com/rwojsznis/sidekiq-lock/issues/4) (I just realized how old this repo is, and how old I am! 👴 ) - please let me know if that answer your question!

**Comment by rwojsznis** [comment]
Oh right, the latter [was discussed in 2021](https://github.com/rwojsznis/sidekiq-lock/issues/12) 😄 

But it seems at first glance that you're looking for something more of general use, like [redlock](https://github.com/leandromoreira/redlock-rb) for example 🤔

**Comment by abdul-wahab-qbatch** [comment]
I have used the simple ruby mutex for that case

**Comment by abdul-wahab-qbatch** [comment]
Also, is there any contribution needed, I would love to do so
